feat: upgrade metering stack to 2024.1 (#398)
* feat: add postgres operator and cluster

* feat: update postgres operator to 1.12.2

* fix: bump shared buffers max conns and vol size

* fix: add cluster to pg system ns

* fix: use new postgres-cluster hostname

* fix: move cluster to openstack namespace

The service is being looked for here

* fix: disable deprecated ha queues

* fix: explicitly set durable queues false

* fix: disable amqp durable queues for cinder

* fix: make admin endpoint keystone-api

keystone is not a valid endpoint with a DNS entry but keystone-api is

* feat: begin to add custom gnocchi container

* feat: add gh workflow for building gnocchi

* fix: convert repo name to lowercase

* feat: replace gnocchi api image with custom one

* fix: apache2 needs this to start

* fix: install apache2-mod-wsgi after py3

* fix: need the gnocchi user to exist

* fix: update path to gnocchi module

* fix: push events don't inherit default inputs

* fix: only build on push if container changed

* fix: specify required drivers during install

* fix: pass default push_version to build-args

* fix: add apt dependencies for source builds

* fix: dir is created automatically now

* fix: memcache is required by keystone

* fix: pymemcache is also needed

* fix: redirect apache2 errorlog to stderr

* feat: update remaining image tags

* fix: db-init expects python

* fix: pymysql is needed by db-init

* fix: sqlalchemy>2 has breaking changes

e.g. `AttributeError: 'Engine' object has no attribute 'execute'`

* fix: re-enable db-init job

* fix: refactor image tag name and build version opt

* fix: normalize image tag name

* fix: reduce gnocchi image footprint

* feat: let changes to main branch trigger build

Scoped to only changes in the release and/or container file of course.

* feat: begin to add custom ceilometer image

* fix: update ceilometer tags to custom image

* fix: add additional requirements for ceilometer

* fix: update event definitions to match 2024.1

* fix: update gnocchi_resources to match 2024.1

* fix: update meters to match 2024.1

* fix: replace remaining images with 2024.1

* fix: remove duplicate dictionary from ipmi

* fix: change event publisher to gnocchi

* feat: add aio overlay for postgres

* docs: add new postgres operator install info

Using an operator is preferred here.

* docs: update gnocchi installation info

Refactor verbiage, add architecture diagram, and improve page layout.

* fix: change repo for gnocchi and ceilometer images

* fix: remove empty line from end of svg